name: fakestore-backend-drf
services:
  app:
    image: eduardosilvasc/fakestore-backend-drf:latest
    environment:
      - MODE=DEVELOPMENT #  possible values are: DEVELOPMENT, PRODUCTION, MIGRATE
      - SECRET_KEY=9-s=%xi$8!a#8=*6poe3cf*wxb8quc83f81tv(6^&2h@@=6wuo
      - DEBUG=True #  possible values are: True, False
      - PASSAGE_APP_ID=rbeVrBpldNWdXTIGGYLshTDR
      - PASSAGE_API_KEY=l9g6N967L5.4s85engArkUWmsyVQWyUzOer6UTXqQua2YPSeS0zpVxa43hEdvzCoSHkdskh7jvX
    ports:
      - 8000:8000
